### ISSUE TITLE
Possible merger with SAMRI?

### ISSUE THREAD

**Issue by TheChymera** [spisakt/ratpype#2]
Hi @spisakt !

I recently came across this project. A couple of colleagues and myself are also working on a standardized pipeline package for small animal imaging, [SAMRI](https://github.com/IBT-FMI/SAMRI) - also using nipype and predominantly FSL as a backend. Though we are looking to migrate more and more towards pure-Python as time goes by.

I was wondering whether you would be intrersted to merge the projects. Our initial pipelines were developed for mice, and we have now started extending our work a bit into rats. Including your work and expertise would definitely help increase the impact and maintainability of both your and our work!

**Comment by spisakt** [comment]
Hi @TheChymera !

Thank you for your interest.
Unfortunately, this development has been discontinued at a quite early stage of development.
I will contact you soon with further details regrading possibilities to collaborate.

Tamas
